# Mathematics for Python

### Matrix
A matrix is a collection of numbers ordered in rows and columns. It can omly contain numbers, symbols, or expressions. Matrices are generally 2 dimensional\
A ```m x n``` matrix contains ```m``` rows and ```n``` columns

### Scalars
A matrix with 1 row and 1 column is a scalar. It is a matrix with only one element and hence, has 0 dimension.\
All numbers we know from algebra are referred to as scalars in linear algebra

### Vectors
Vectors are matrices with only one dimension. \
They are either **column vectors** i.e. ```m x 1``` or **row vectors** i.e. ```1 x n```. \
The number of elements in a vector is called the length of the vector.

With this logic:
- Scalars have 0 dimension consisting of only one element.
- Vectors have 1 dimension and are a collection of scalars.
- Matrices have 2 dimensions and are a collection of multiple vectors.

## Tensor

Tensors are simply a generalization of the concepts we have seen so far.
- Rank 0 tensors : 1 x 1 ...................... Scalars
- Rank 1 tensors : m x 1 or 1 x m ........... Vectors
- Rank 2 tensors : m x n ....................... Matrices
- Rank 3 tensors : k x m x n   ......... and so on...


## Array
In computer science, an array is a fundamental data structure that stores a collection of elements, typically of the same data type, in contiguous memory locations. It is a linear data structure where all elements are arranged sequentially.\
\
Scalars, vectors, matrices, and tensors are mathematical entities representing different levels of data complexity and dimensions, where a scalar is a single number (0-dimensional), a vector is a 1-dimensional array, a matrix is a 2-dimensional array, and a tensor is a general n-dimensional array that encompasses scalars, vectors, and matrices as special cases.

### Importing NumPy library
In Python, performing mathematical operations on arrays is most efficiently done using the **```NumPy```** library. NumPy provides a powerful ```ndarray``` object, which is a multidimensional array optimized for numerical computations.

In [1]:
import numpy as np

## Creating Scalars, Vectors, and Matrices

### Scalars

In [2]:
s = 5

In [3]:
s

5

### Vectors

In [4]:
v = np.array([5, -2, 4])

In [5]:
v

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Tensor

In [17]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [18]:
m1.shape

(2, 3)

In [19]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [20]:
m2.shape

(2, 3)

In [21]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [22]:
t.shape

(2, 2, 3)

#### Creating an n-dimensional tensor manually

In [23]:
t2 = np.array([[[5, 12, 6], [-3, 0, 14]], [[9, 8, 7], [1, 3, -5]]])
t2

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [24]:
t2.shape

(2, 2, 3)

## Data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(s)
s_array

array(5)

## Data Shapes

In [12]:
m.shape

(2, 3)

In [13]:
v.shape

(3,)

## Creating a column vector

In [14]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [15]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [16]:
s_array.shape

()

## Adding and Subtracting Matrices

### Addition
Adds corresponding elements of matrices. Should have same shape

In [25]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [26]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Subtraction

Similar to addition. Should have same shape

In [28]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [30]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### more...

In [31]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [32]:
v1 + v2

array([6, 6, 6, 6, 6])

In [33]:
v1 - v2

array([-4, -2,  0,  2,  4])

## With Scalars

### Addition of Scalars

In [34]:
5 + 5

10

In [35]:
10 - 4

6

### Addition of Matrices or Vector WITH a Scalar

In [36]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [37]:
m1 + 2

array([[ 7, 14,  8],
       [-1,  2, 16]])

In [38]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [39]:
m2 - 1

array([[ 8,  7,  6],
       [ 0,  2, -6]])

In [40]:
v1

array([1, 2, 3, 4, 5])

In [41]:
v1 + 4

array([5, 6, 7, 8, 9])

In [42]:
v2

array([5, 4, 3, 2, 1])

In [43]:
v2 - 2

array([ 3,  2,  1,  0, -1])

In [44]:
m1 + np.array([2])

array([[ 7, 14,  8],
       [-1,  2, 16]])

## Transpose
Transposing turns all the rows of a matrix into cloumns and vice versa.\
An ```m x n``` matrix transposed becomes a ```n x m``` matrix

### Transposing Matrices

In [45]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [46]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [47]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [48]:
m2.T

array([[ 9,  1],
       [ 8,  3],
       [ 7, -5]])

### Transposing Vectors

In [49]:
v1

array([1, 2, 3, 4, 5])

In [50]:
v1.T

array([1, 2, 3, 4, 5])

In [51]:
v1.shape

(5,)

In [52]:
v1.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [53]:
v1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

### Transposing Tensors

In [54]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [55]:
t.shape

(2, 2, 3)

In [56]:
t.T

array([[[ 5,  9],
        [-3,  1]],

       [[12,  8],
        [ 0,  3]],

       [[ 6,  7],
        [14, -5]]])

In [57]:
t.T.shape

(3, 2, 2)

## Multiplication

### Scalar * Scalar

In [58]:
6 * 5

30

In [59]:
10 * -2

-20

In [60]:
np.array([5]) * np.array([8])

array([40])

In [61]:
np.dot(5,6)

np.int64(30)

In [62]:
np.dot(10,-2)

np.int64(-20)

### Vectors - Dot Product
The condition is that the vectors must have same length.\
Dot product is Sum of the Products of the corresponding elements.

In [63]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [64]:
np.dot(x, y)      # (2*10) + (8*-7) + (-4*3) = -66

np.int64(-66)

In [65]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

np.dot(u,v)

np.int64(18)

### Scalar * Vector

In [66]:
x

array([ 2,  8, -4])

In [67]:
5 * x

array([ 10,  40, -20])

In [68]:
np.dot(5,x)

array([ 10,  40, -20])

### Scalar * Matrix

In [69]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [70]:
m1 * 2

array([[10, 24, 12],
       [-6,  0, 28]])

In [71]:
3 * m1

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrices - Dot Product
We can only multiply an ```m x n``` matrix with an ```n x k``` matrix.\
The result of this multiplication will be an ```m x k``` matrix.\
\
For eg. 
- ```2 x 3``` . ```3 x 6``` = ```2 x 6``` matrix
- ```3 x 4``` . ```4 x 2``` = ```3 x 2``` matrix
- ```100 x 300``` . ```300 x 3``` = ```100 x 3``` matrix


In [72]:
a = np.array([[5,12,6],
              [-3,0,14]])
b = np.array([[2, -1],
              [8, 0],
              [3, 0]])
a, b

(array([[ 5, 12,  6],
        [-3,  0, 14]]),
 array([[ 2, -1],
        [ 8,  0],
        [ 3,  0]]))

In [73]:
a.shape, b.shape

((2, 3), (3, 2))

In [74]:
np.dot(a,b)

array([[124,  -5],
       [ 36,   3]])

In [75]:
x = np.array([[-12, 5, 5, 1, 6], [6, -2, 0, 0, -3], [10, 2, 0, 8, 0], [9, -4, 8, 3, -6]])
y = np.array([[6, -1], [8, -4], [2, -2], [7, 4], [-6, -9]])

x, y

(array([[-12,   5,   5,   1,   6],
        [  6,  -2,   0,   0,  -3],
        [ 10,   2,   0,   8,   0],
        [  9,  -4,   8,   3,  -6]]),
 array([[ 6, -1],
        [ 8, -4],
        [ 2, -2],
        [ 7,  4],
        [-6, -9]]))

In [76]:
x.shape, y.shape

((4, 5), (5, 2))

In [77]:
np.dot(x,y), np.dot(x,y).shape

(array([[-51, -68],
        [ 38,  29],
        [132,  14],
        [ 95,  57]]),
 (4, 2))